# This file is included early in main Makefile, don't set any targets
# to avoid overriding default (all) target

# Project definitions
REPO_NAME := Finnish Trams
BASE_FILENAME := finnishtrams
NMLC_MONKEY := true
