# Definition of the grfs
REPO_NAME           ?= Finnish Trams

# This is the filename part common to the grf file, main source file and the tar name
BASE_FILENAME       ?= finnishtrams

# Documentation files
DOC_FILES ?= docs/readme.txt docs/license.txt docs/license_makefile.txt docs/changelog.txt

# Possible offset to NewGRF version. Increase by one, if a release
# branch is added to the repository
REPO_BRANCH_VERSION ?= 0

# Directory structure
SCRIPT_DIR          ?= scripts

# Uncomment in order to make use of gimp scripting. See the file
# for a description of the format
GFX_SCRIPT_LIST_FILES      := gfx/trams.xcf2png

# If needed, declare the minimum NML requirements
# REQUIRED_NML_BRANCH  = 0.3
# MIN_NML_REVISION     = 0
