#!/usr/bin/env python3

import glob
import os

import cons_parser

this_dir = os.path.normpath(os.path.dirname(__file__))

for cons in glob.glob(os.path.join(this_dir, 'vehs', '*.cons')):
    with open(cons) as f:
        parser = cons_parser.Parser(f.read())
    print(cons)
